export const IPC_NAMES = {
  WINDOW_EVENT: "WINDOW_EVENT",
  HANDLE_STORE: "HANDLE_STORE",
  HANDLE_LANGUAGE: "HANDLE_LANGUAGE",
  HANDLE_GLOBAL_VARIABLE: "HANDLE_GLOBAL_VARIABLE",
  WILL_QUIT: "WILL_QUIT",
};

export const IPC_TYPES = {
  WINDOW_EVENT: {
    WINDOW_MINIMIZE: "WINDOW_MINIMIZE",
    WINDOW_CLOSE: "WINDOW_CLOSE",
    WINDOW_MAXIMIZED: "WINDOW_MAXIMIZED",
    WINDOW_IS_MAXIMIZED: "WINDOW_IS_MAXIMIZED",
  },
  HANDLE_STORE: {
    SET_KEY: "SET_KEY",
    GET_KEY: "GET_KEY",
    CLEAR_ALL: "CLEAR_ALL",
    DELETE_KEY: "DELETE_KEY",
    RESET_KEY: "RESET_KEY",
    HAS_KEY: "RESET_KEY",
  },
  HANDLE_LANGUAGE: {
    GET_LANGUAGE_INFO: "GET_LANGUAGE_INFO",
    CHANGE_CURRENT_LANGUAGE: "CHANGE_CURRENT_LANGUAGE",
  },
  HANDLE_GLOBAL_VARIABLE: {
    GET_KEY: "GET_KEY",
    SET_KEY: "SET_KEY",
  },
};
