export enum IPC_NAMES {
  WINDOW_EVENT = "WINDOW_EVENT",
  HANDLE_LANGUAGE = "HANDLE_LANGUAGE",
  HANDLE_STORE = "HANDLE_STORE",
  HANDLE_GLOBAL_VARIABLE = "HANDLE_GLOBAL_VARIABLE",
  WILL_QUIT = "WILL_QUIT",
};

export const IPC_TYPES = {
  WINDOW_EVENT: {
    WINDOW_MINIMIZE: "WINDOW_MINIMIZE",
    WINDOW_CLOSE: "WINDOW_CLOSE",
    WINDOW_MAXIMIZED: "WINDOW_MAXIMIZED",
    WINDOW_IS_MAXIMIZED: "WINDOW_IS_MAXIMIZED",
  },
  HANDLE_STORE: {
    SET_ITEMS: "SET_ITEMS",
    GET_ALL_ITEMS: "GET_ALL_ITEMS",
    RESET_ALL_ITEMS: "RESET_ALL_ITEMS",
    DELETE_ITEMS: "DELETE_ITEMS",
    RESET_ITEMS: "RESET_ITEMS",
  },
  HANDLE_LANGUAGE: {
    GET_LANGUAGE_INFO: "GET_LANGUAGE_INFO",
    CHANGE_CURRENT_LANGUAGE: "CHANGE_CURRENT_LANGUAGE",
  },
  HANDLE_GLOBAL_VARIABLE: {
    GET_ALL_VARIABLES: "GET_ALL_VARIABLES",
    SET_VARIABLES: "SET_VARIABLES",
  },
};
